# Generated by Django 5.2.17 on 2026-08-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_kisasecurityweakness_vulnerability_security_weakness'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='analysis_languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='analysis_language',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='analysis_language',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
