# Generated by Django 5.2.17 on 2026-08-31 13:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0004_backfill_analysis_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisChunkFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_path', models.CharField(max_length=1000)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('file_class', models.CharField(choices=[('normal', 'Normal'), ('large', 'Large'), ('oversized', 'Oversized')], default='normal', max_length=20)),
                ('content_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisDispatchOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_no', models.PositiveIntegerField()),
                ('event_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('publish_attempts', models.PositiveIntegerField(default=0)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_error', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('planning', 'Planning'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='AnalysisChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('sequence', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('retry_pending', 'Retry Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('file_count', models.PositiveIntegerField(default=0)),
                ('total_bytes', models.PositiveBigIntegerField(default=0)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('status_reason', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('failure_reason', models.TextField(blank=True)),
                ('logs', models.TextField(blank=True)),
                ('raw_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_chunks', to='scans.analysisrun')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisChunkAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.PositiveIntegerField()),
                ('execution_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('worker_lost', 'Worker Lost'), ('timed_out', 'Timed Out'), ('cancelled', 'Cancelled'), ('superseded', 'Superseded')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('heartbeat_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_expires_at', models.DateTimeField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('failure_reason', models.TextField(blank=True)),
                ('logs', models.TextField(blank=True)),
                ('raw_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='scans.analysischunk')),
            ],
            options={
                'ordering': ['attempt_no'],
            },
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='analysis_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='scans.analysischunkattempt'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['analysis_run', 'analysis_attempt'], name='vuln_run_attempt_idx'),
        ),
        migrations.AddConstraint(
            model_name='vulnerability',
            constraint=models.UniqueConstraint(condition=models.Q(('analysis_attempt__isnull', False), ('fingerprint__isnull', False)), fields=('analysis_attempt', 'fingerprint'), name='unique_attempt_vulnerability_fingerprint'),
        ),
        migrations.AddField(
            model_name='analysischunkfile',
            name='chunk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='scans.analysischunk'),
        ),
        migrations.AddField(
            model_name='analysisdispatchoutbox',
            name='chunk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_outboxes', to='scans.analysischunk'),
        ),
        migrations.AddIndex(
            model_name='analysischunk',
            index=models.Index(fields=['analysis_run', 'status'], name='chunk_run_status_idx'),
        ),
        migrations.AddIndex(
            model_name='analysischunk',
            index=models.Index(fields=['status', 'updated_at'], name='chunk_status_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='analysischunk',
            constraint=models.UniqueConstraint(fields=('analysis_run', 'sequence'), name='unique_analysis_run_chunk_sequence'),
        ),
        migrations.AddIndex(
            model_name='analysischunkattempt',
            index=models.Index(fields=['status', 'lease_expires_at'], name='attempt_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='analysischunkattempt',
            index=models.Index(fields=['chunk', 'status'], name='attempt_chunk_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='analysischunkattempt',
            constraint=models.UniqueConstraint(fields=('chunk', 'attempt_no'), name='unique_chunk_attempt_number'),
        ),
        migrations.AddConstraint(
            model_name='analysischunkattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('chunk',), name='unique_running_attempt_per_chunk'),
        ),
        migrations.AddConstraint(
            model_name='analysischunkattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'completed')), fields=('chunk',), name='unique_completed_attempt_per_chunk'),
        ),
        migrations.AddIndex(
            model_name='analysischunkfile',
            index=models.Index(fields=['chunk', 'file_class'], name='chunk_file_class_idx'),
        ),
        migrations.AddConstraint(
            model_name='analysischunkfile',
            constraint=models.UniqueConstraint(fields=('chunk', 'relative_path'), name='unique_chunk_relative_path'),
        ),
        migrations.AddIndex(
            model_name='analysisdispatchoutbox',
            index=models.Index(fields=['status', 'available_at'], name='outbox_dispatch_idx'),
        ),
        migrations.AddConstraint(
            model_name='analysisdispatchoutbox',
            constraint=models.UniqueConstraint(fields=('chunk', 'dispatch_no'), name='unique_chunk_dispatch_number'),
        ),
    ]
