# Generated by Django 5.2.17 on 2026-09-16 06:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def backfill_chunk_v1(apps, schema_editor):
    AnalysisRun = apps.get_model('scans', 'AnalysisRun')
    AnalysisRun.objects.filter(pipeline_version__isnull=True).update(
        pipeline_version='chunk_v1'
    )


def reverse_pipeline_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0005_analysischunkfile_analysisdispatchoutbox_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.PositiveIntegerField()),
                ('execution_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('worker_lost', 'Worker lost'), ('timed_out', 'Timed out'), ('cancelled', 'Cancelled'), ('superseded', 'Superseded')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('heartbeat_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_expires_at', models.DateTimeField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('logs', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='finding_fingerprint_version',
            field=models.CharField(default='v2', max_length=10),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='pipeline_version',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.RunPython(
            backfill_chunk_v1,
            reverse_pipeline_backfill,
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='pipeline_version',
            field=models.CharField(choices=[('chunk_v1', 'Chunk v1'), ('repository_v2', 'Repository v2')], db_index=True, default='chunk_v1', max_length=20),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='snapshot_digest',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='ScanExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('scope_kind', models.CharField(default='repository', max_length=20)),
                ('scope_root', models.CharField(default='.', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('retry_pending', 'Retry pending'), ('normalization_pending', 'Normalization pending'), ('normalizing', 'Normalizing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('normalization_retry_count', models.PositiveSmallIntegerField(default=0)),
                ('max_normalization_retries', models.PositiveSmallIntegerField(default=3)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('raw_occurrence_count', models.PositiveIntegerField(default=0)),
                ('discovered_supported', models.PositiveIntegerField(default=0)),
                ('coverage', models.JSONField(blank=True, default=dict)),
                ('coverage_complete', models.BooleanField(default=False)),
                ('status_reason', models.CharField(blank=True, default='', max_length=80)),
                ('engine', models.CharField(default='semgrep', max_length=30)),
                ('engine_version', models.CharField(blank=True, default='', max_length=40)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('snapshot_digest', models.CharField(blank=True, default='', max_length=64)),
                ('ruleset_digest', models.CharField(blank=True, default='', max_length=64)),
                ('options_digest', models.CharField(blank=True, default='', max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scan_execution', to='scans.analysisrun')),
            ],
        ),
        migrations.CreateModel(
            name='ScanDispatchOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('engine', 'Engine'), ('normalization', 'Normalization')], max_length=20)),
                ('dispatch_no', models.PositiveIntegerField()),
                ('event_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('task_name', models.CharField(max_length=120)),
                ('deterministic_task_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('publish_attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_publish_attempts', models.PositiveSmallIntegerField(default=5)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('claim_deadline_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_outboxes', to='scans.scanattempt')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_outboxes', to='scans.scanexecution')),
            ],
        ),
        migrations.AddField(
            model_name='scanattempt',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='scans.scanexecution'),
        ),
        migrations.CreateModel(
            name='ScanArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('semgrep_json', 'Semgrep JSON'), ('diagnostic', 'Diagnostic')], default='semgrep_json', max_length=30)),
                ('state', models.CharField(choices=[('writing', 'Writing'), ('ready', 'Ready'), ('invalid', 'Invalid'), ('deleted', 'Deleted')], default='writing', max_length=20)),
                ('is_canonical', models.BooleanField(default=False)),
                ('relative_path', models.CharField(blank=True, default='', max_length=500)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('content_type', models.CharField(default='application/json', max_length=100)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='scans.scanattempt')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='scans.scanexecution')),
            ],
        ),
        migrations.CreateModel(
            name='ScanFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_version', models.CharField(default='v2', max_length=10)),
                ('aggregate_fingerprint', models.CharField(max_length=64)),
                ('lineage_signature', models.CharField(db_index=True, max_length=64)),
                ('rule_id', models.CharField(max_length=255)),
                ('language', models.CharField(blank=True, default='', max_length=50)),
                ('file_path', models.CharField(max_length=1000)),
                ('start_line', models.PositiveIntegerField(default=1)),
                ('start_column', models.PositiveIntegerField(default=1)),
                ('end_line', models.PositiveIntegerField(default=1)),
                ('end_column', models.PositiveIntegerField(default=1)),
                ('severity', models.CharField(blank=True, default='', max_length=30)),
                ('message', models.TextField(blank=True)),
                ('canonical_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_findings', to='scans.analysisrun')),
            ],
        ),
        migrations.CreateModel(
            name='ScanNormalizationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.PositiveIntegerField()),
                ('execution_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('worker_lost', 'Worker lost'), ('timed_out', 'Timed out'), ('cancelled', 'Cancelled')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('heartbeat_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_expires_at', models.DateTimeField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('logs', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalization_attempts', to='scans.scanexecution')),
            ],
        ),
        migrations.CreateModel(
            name='ScanOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_key', models.CharField(max_length=64)),
                ('raw_result_index', models.PositiveIntegerField()),
                ('raw_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='scans.scanartifact')),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='scans.scanfinding')),
            ],
        ),
        migrations.AddConstraint(
            model_name='scanexecution',
            constraint=models.CheckConstraint(condition=models.Q(('sequence', 1)), name='scan_execution_sequence_one'),
        ),
        migrations.AddConstraint(
            model_name='scanexecution',
            constraint=models.CheckConstraint(condition=models.Q(('scope_kind', 'repository')), name='scan_execution_repository_scope'),
        ),
        migrations.AddConstraint(
            model_name='scanexecution',
            constraint=models.CheckConstraint(condition=models.Q(('scope_root', '.')), name='scan_execution_root_dot'),
        ),
        migrations.AddConstraint(
            model_name='scanexecution',
            constraint=models.CheckConstraint(condition=models.Q(('retry_count__lte', models.F('max_retries'))), name='scan_execution_retry_bounds'),
        ),
        migrations.AddConstraint(
            model_name='scanexecution',
            constraint=models.CheckConstraint(condition=models.Q(('normalization_retry_count__lte', models.F('max_normalization_retries'))), name='scan_normalization_retry_bounds'),
        ),
        migrations.AddConstraint(
            model_name='scandispatchoutbox',
            constraint=models.UniqueConstraint(fields=('execution', 'kind', 'dispatch_no'), name='unique_scan_dispatch_number'),
        ),
        migrations.AddConstraint(
            model_name='scandispatchoutbox',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('execution', 'kind'), name='unique_pending_scan_dispatch'),
        ),
        migrations.AddConstraint(
            model_name='scandispatchoutbox',
            constraint=models.CheckConstraint(condition=models.Q(('publish_attempts__lte', models.F('max_publish_attempts'))), name='scan_dispatch_publish_bounds'),
        ),
        migrations.AddConstraint(
            model_name='scanattempt',
            constraint=models.UniqueConstraint(fields=('execution', 'attempt_no'), name='unique_scan_attempt_number'),
        ),
        migrations.AddConstraint(
            model_name='scanattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('execution',), name='unique_running_scan_attempt'),
        ),
        migrations.AddConstraint(
            model_name='scanattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'completed')), fields=('execution',), name='unique_completed_scan_attempt'),
        ),
        migrations.AddConstraint(
            model_name='scanartifact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_canonical', True), ('kind', 'semgrep_json')), fields=('execution',), name='unique_canonical_scan_artifact'),
        ),
        migrations.AddConstraint(
            model_name='scanfinding',
            constraint=models.UniqueConstraint(fields=('analysis_run', 'fingerprint_version', 'aggregate_fingerprint'), name='unique_scan_aggregate_fingerprint'),
        ),
        migrations.AddConstraint(
            model_name='scannormalizationattempt',
            constraint=models.UniqueConstraint(fields=('execution', 'attempt_no'), name='unique_normalization_attempt_number'),
        ),
        migrations.AddConstraint(
            model_name='scannormalizationattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('execution',), name='unique_running_normalization_attempt'),
        ),
        migrations.AddConstraint(
            model_name='scannormalizationattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'completed')), fields=('execution',), name='unique_completed_normalization_attempt'),
        ),
        migrations.AddConstraint(
            model_name='scanoccurrence',
            constraint=models.UniqueConstraint(fields=('artifact', 'occurrence_key'), name='unique_scan_occurrence_key'),
        ),
        migrations.AddConstraint(
            model_name='scanoccurrence',
            constraint=models.UniqueConstraint(fields=('artifact', 'raw_result_index'), name='unique_scan_raw_result_index'),
        ),
    ]
