# Generated by Django 5.2.17 on 2026-09-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0006_scanattempt_analysisrun_finding_fingerprint_version_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='scanartifact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', 'ready'), _negated=True), models.Q(('published_at__isnull', False), ('size_bytes__gt', 0), models.Q(('relative_path', ''), _negated=True), models.Q(('sha256', ''), _negated=True)), _connector='OR'), name='scan_artifact_ready_metadata'),
        ),
        migrations.AddConstraint(
            model_name='scanattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('status', 'running')), models.Q(('completed_at__isnull', False), ('status__in', ['completed', 'failed', 'worker_lost', 'timed_out', 'cancelled', 'superseded'])), _connector='OR'), name='scan_attempt_status_time'),
        ),
        migrations.AddConstraint(
            model_name='scanexecution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('status__in', ['completed', 'failed', 'cancelled'])), models.Q(('completed_at__isnull', True), ('status__in', ['pending', 'queued', 'running', 'retry_pending', 'normalization_pending', 'normalizing'])), _connector='OR'), name='scan_execution_terminal_time'),
        ),
        migrations.AddConstraint(
            model_name='scannormalizationattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('status', 'running')), models.Q(('completed_at__isnull', False), ('status__in', ['completed', 'failed', 'worker_lost', 'timed_out', 'cancelled'])), _connector='OR'), name='normalization_attempt_status_time'),
        ),
    ]
