# Generated by Django 5.2.17 on 2026-09-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0007_scanartifact_scan_artifact_ready_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanattempt',
            name='process_group_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
