# Generated by Django 5.2.17 on 2026-09-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scans", "0008_scanattempt_process_group_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanartifact",
            name="attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="artifacts",
                to="scans.scanattempt",
            ),
        ),
    ]
