# Generated by Django 5.2.17 on 2026-08-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceversion',
            name='detected_languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='sourceversion',
            name='language',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
