# KISA 소프트웨어 개발보안 가이드(2021.12.29)
# 구현단계 보안약점 제거 기준 49개 Master Data
#
# identifier는 카테고리 기반 서비스 코드로 통일한다.
# 예: KISA-INP-01, KISA-SEC-06, KISA-API-02
# item_number는 KISA 원본 전체 순번 1~49를 유지한다.

KISA_SECURITY_WEAKNESSES = [{'item_number': 1,
  'identifier': 'KISA-INP-01',
  'category': '입력데이터 검증 및 표현',
  'name': 'SQL 삽입',
  'description': 'SQL 질의문을 생성할 때 검증되지 않은 외부 입력 값을 허용하여 악의적인 질의문이 실행 가능한 보안약점'},
 {'item_number': 2,
  'identifier': 'KISA-INP-02',
  'category': '입력데이터 검증 및 표현',
  'name': '코드 삽입',
  'description': '프로세스가 외부 입력 값을 코드 또는 명령어로 해석·실행할 수 있고 검증되지 않은 외부 입력 값을 허용한 경우 악의적인 코드가 실행 가능한 '
                 '보안약점'},
 {'item_number': 3,
  'identifier': 'KISA-INP-03',
  'category': '입력데이터 검증 및 표현',
  'name': '경로 조작 및 자원 삽입',
  'description': '시스템 자원 접근경로 또는 자원제어 명령어에 검증되지 않은 외부 입력값을 허용하여 시스템 자원에 무단 접근 및 악의적인 행위가 가능한 보안약점'},
 {'item_number': 4,
  'identifier': 'KISA-INP-04',
  'category': '입력데이터 검증 및 표현',
  'name': '크로스사이트 스크립트',
  'description': '사용자 브라우저에 검증되지 않은 외부 입력값을 허용하여 악의적인 스크립트가 실행 가능한 보안약점'},
 {'item_number': 5,
  'identifier': 'KISA-INP-05',
  'category': '입력데이터 검증 및 표현',
  'name': '운영체제 명령어 삽입',
  'description': '운영체제 명령어를 생성할 때 검증되지 않은 외부 입력값을 허용하여 악의적인 명령어가 실행 가능한 보안약점'},
 {'item_number': 6,
  'identifier': 'KISA-INP-06',
  'category': '입력데이터 검증 및 표현',
  'name': '위험한 형식 파일 업로드',
  'description': '파일의 확장자 등 파일형식에 대한 검증 없이 파일 업로드를 허용하여 공격이 가능한 보안약점'},
 {'item_number': 7,
  'identifier': 'KISA-INP-07',
  'category': '입력데이터 검증 및 표현',
  'name': '신뢰되지 않는 URL 주소로 자동접속 연결',
  'description': 'URL 링크 생성에 검증되지 않은 외부 입력값을 허용하여 악의적인 사이트로 자동 접속 가능한 보안약점'},
 {'item_number': 8,
  'identifier': 'KISA-INP-08',
  'category': '입력데이터 검증 및 표현',
  'name': '부적절한 XML 외부 개체 참조',
  'description': '임의로 조작된 XML 외부개체에 대한 적절한 검증 없이 참조를 허용하여 공격이 가능한 보안약점'},
 {'item_number': 9,
  'identifier': 'KISA-INP-09',
  'category': '입력데이터 검증 및 표현',
  'name': 'XML 삽입',
  'description': 'XQuery, XPath 질의문을 생성할 때 검증되지 않은 외부 입력값을 허용하여 악의적인 질의문이 실행 가능한 보안약점'},
 {'item_number': 10,
  'identifier': 'KISA-INP-10',
  'category': '입력데이터 검증 및 표현',
  'name': 'LDAP 삽입',
  'description': 'LDAP 명령문을 생성할 때 검증되지 않은 외부 입력 값을 허용하여 악의적인 명령어가 실행 가능한 보안약점'},
 {'item_number': 11,
  'identifier': 'KISA-INP-11',
  'category': '입력데이터 검증 및 표현',
  'name': '크로스사이트 요청 위조',
  'description': '사용자 브라우저에 검증되지 않은 외부 입력 값을 허용하여 사용자의 의지와 무관하게 공격자가 의도한 행위가 실행 가능한 보안약점'},
 {'item_number': 12,
  'identifier': 'KISA-INP-12',
  'category': '입력데이터 검증 및 표현',
  'name': '서버사이드 요청 위조',
  'description': '서버 간 처리되는 요청에 검증되지 않은 외부 입력값을 허용하여 공격자가 의도한 서버로 전송하거나 변조하는 보안약점'},
 {'item_number': 13,
  'identifier': 'KISA-INP-13',
  'category': '입력데이터 검증 및 표현',
  'name': 'HTTP 응답분할',
  'description': 'HTTP 응답헤더에 개행문자가 포함된 검증되지 않은 외부 입력값을 허용하여 악의적인 코드가 실행 가능한 보안약점'},
 {'item_number': 14,
  'identifier': 'KISA-INP-14',
  'category': '입력데이터 검증 및 표현',
  'name': '정수형 오버플로우',
  'description': '정수형 변수에 저장된 값이 허용된 정수 값 범위를 벗어나 프로그램이 예기치 않게 동작 가능한 보안약점'},
 {'item_number': 15,
  'identifier': 'KISA-INP-15',
  'category': '입력데이터 검증 및 표현',
  'name': '보안기능 결정에 사용되는 부적절한 입력값',
  'description': '보안기능 결정에 검증되지 않은 외부 입력값을 허용하여 인증 또는 권한부여 등의 보안기능을 우회하는 보안약점'},
 {'item_number': 16,
  'identifier': 'KISA-INP-16',
  'category': '입력데이터 검증 및 표현',
  'name': '메모리 버퍼 오버플로우',
  'description': '메모리 버퍼의 경계값을 넘어서 메모리 값을 읽거나 저장하여 예기치 않은 결과가 발생하는 보안약점'},
 {'item_number': 17,
  'identifier': 'KISA-INP-17',
  'category': '입력데이터 검증 및 표현',
  'name': '포맷 스트링 삽입',
  'description': 'printf 등 포맷 스트링 제어함수에 검증되지 않은 외부 입력값을 허용하여 발생하는 보안약점'},
 {'item_number': 18,
  'identifier': 'KISA-SEC-01',
  'category': '보안기능',
  'name': '적절한 인증 없는 중요 기능 허용',
  'description': '중요정보를 적절한 인증 없이 열람하거나 변경할 수 있는 보안약점'},
 {'item_number': 19,
  'identifier': 'KISA-SEC-02',
  'category': '보안기능',
  'name': '부적절한 인가',
  'description': '중요자원에 접근할 때 적절한 제어가 없어 비인가자의 접근이 가능한 보안약점'},
 {'item_number': 20,
  'identifier': 'KISA-SEC-03',
  'category': '보안기능',
  'name': '중요한 자원에 대한 잘못된 권한 설정',
  'description': '중요자원에 적절한 접근 권한을 부여하지 않아 중요정보가 노출되거나 수정 가능한 보안약점'},
 {'item_number': 21,
  'identifier': 'KISA-SEC-04',
  'category': '보안기능',
  'name': '취약한 암호화 알고리즘 사용',
  'description': '중요정보의 기밀성을 보장할 수 없는 취약한 암호화 알고리즘을 사용하여 정보가 노출 가능한 보안약점'},
 {'item_number': 22,
  'identifier': 'KISA-SEC-05',
  'category': '보안기능',
  'name': '암호화되지 않은 중요정보',
  'description': '중요정보 전송 시 암호화 또는 안전한 통신채널을 이용하지 않거나 저장 시 암호화하지 않아 정보가 노출 가능한 보안약점'},
 {'item_number': 23,
  'identifier': 'KISA-SEC-06',
  'category': '보안기능',
  'name': '하드코드된 중요정보',
  'description': '소스코드에 비밀번호, 암호화키 등의 중요정보를 직접 코딩하여 소스코드 유출 시 중요정보가 노출되고 주기적 변경이 어려운 보안약점'},
 {'item_number': 24,
  'identifier': 'KISA-SEC-07',
  'category': '보안기능',
  'name': '충분하지 않은 키 길이 사용',
  'description': '암호화 등에 사용되는 키의 길이가 충분하지 않아 데이터의 기밀성·무결성을 보장할 수 없는 보안약점'},
 {'item_number': 25,
  'identifier': 'KISA-SEC-08',
  'category': '보안기능',
  'name': '적절하지 않은 난수 값 사용',
  'description': '사용한 난수가 예측 가능하여 공격자가 다음 난수를 예상해 시스템을 공격 가능한 보안약점'},
 {'item_number': 26,
  'identifier': 'KISA-SEC-09',
  'category': '보안기능',
  'name': '취약한 비밀번호 허용',
  'description': '비밀번호 조합규칙이 미흡하거나 길이가 충분하지 않아 비밀번호가 노출 가능한 보안약점'},
 {'item_number': 27,
  'identifier': 'KISA-SEC-10',
  'category': '보안기능',
  'name': '부적절한 전자서명 확인',
  'description': '프로그램, 라이브러리, 코드의 전자서명에 대한 유효성 검증이 적절하지 않아 공격자의 악의적인 코드가 실행 가능한 보안약점'},
 {'item_number': 28,
  'identifier': 'KISA-SEC-11',
  'category': '보안기능',
  'name': '부적절한 인증서 유효성 검증',
  'description': '인증서에 대한 유효성 검증이 적절하지 않아 발생하는 보안약점'},
 {'item_number': 29,
  'identifier': 'KISA-SEC-12',
  'category': '보안기능',
  'name': '사용자 하드디스크에 저장되는 쿠키를 통한 정보노출',
  'description': '세션 ID, 사용자 권한정보 등 중요정보를 포함한 쿠키가 사용자 하드디스크에 저장되어 중요정보가 노출 가능한 보안약점'},
 {'item_number': 30,
  'identifier': 'KISA-SEC-13',
  'category': '보안기능',
  'name': '주석문 안에 포함된 시스템 주요정보',
  'description': '소스코드 주석문에 인증정보 등 시스템 주요정보가 포함되어 소스코드 노출 시 주요정보도 노출 가능한 보안약점'},
 {'item_number': 31,
  'identifier': 'KISA-SEC-14',
  'category': '보안기능',
  'name': '솔트 없이 일방향 해쉬 함수 사용',
  'description': '솔트를 사용하지 않고 생성된 해쉬 값에 대해 공격자가 레인보우 테이블을 이용하여 원본 정보를 복원 가능한 보안약점'},
 {'item_number': 32,
  'identifier': 'KISA-SEC-15',
  'category': '보안기능',
  'name': '무결성 검사 없는 코드 다운로드',
  'description': '소스코드 또는 실행파일을 무결성 검사 없이 다운로드 받아 실행하여 공격자의 악의적인 코드가 실행 가능한 보안약점'},
 {'item_number': 33,
  'identifier': 'KISA-SEC-16',
  'category': '보안기능',
  'name': '반복된 인증시도 제한 기능 부재',
  'description': '인증 시도 수를 제한하지 않아 공격자가 반복적으로 임의 값을 입력하여 계정 권한을 획득 가능한 보안약점'},
 {'item_number': 34,
  'identifier': 'KISA-TIM-01',
  'category': '시간 및 상태',
  'name': '경쟁조건 : 검사 시점과 사용 시점(TOCTOU)',
  'description': '멀티 프로세스 상에서 자원을 검사하는 시점과 사용하는 시점이 달라서 발생하는 보안약점'},
 {'item_number': 35,
  'identifier': 'KISA-TIM-02',
  'category': '시간 및 상태',
  'name': '종료되지 않는 반복문 또는 재귀함수',
  'description': '종료조건 없는 제어문 사용으로 반복문 또는 재귀함수가 무한히 반복되어 발생할 수 있는 보안약점'},
 {'item_number': 36,
  'identifier': 'KISA-ERR-01',
  'category': '에러처리',
  'name': '오류 메시지 정보노출',
  'description': '오류메시지나 스택정보에 시스템 내부구조가 포함되어 민감한 정보 또는 디버깅 정보가 노출 가능한 보안약점'},
 {'item_number': 37,
  'identifier': 'KISA-ERR-02',
  'category': '에러처리',
  'name': '오류상황 대응 부재',
  'description': '시스템 오류상황을 처리하지 않아 프로그램 실행정지 등 의도하지 않은 상황이 발생 가능한 보안약점'},
 {'item_number': 38,
  'identifier': 'KISA-ERR-03',
  'category': '에러처리',
  'name': '부적절한 예외 처리',
  'description': '예외사항을 부적절하게 처리하여 의도하지 않은 상황이 발생 가능한 보안약점'},
 {'item_number': 39,
  'identifier': 'KISA-COD-01',
  'category': '코드오류',
  'name': 'Null Pointer 역참조',
  'description': '변수의 주소 값이 Null인 객체를 참조하는 보안약점'},
 {'item_number': 40,
  'identifier': 'KISA-COD-02',
  'category': '코드오류',
  'name': '부적절한 자원 해제',
  'description': '사용 완료된 자원을 해제하지 않아 자원이 고갈되어 새로운 입력을 처리할 수 없는 보안약점'},
 {'item_number': 41,
  'identifier': 'KISA-COD-03',
  'category': '코드오류',
  'name': '해제된 자원 사용',
  'description': '메모리 등 해제된 자원을 참조하여 예기치 않은 오류가 발생하는 보안약점'},
 {'item_number': 42,
  'identifier': 'KISA-COD-04',
  'category': '코드오류',
  'name': '초기화되지 않은 변수 사용',
  'description': '변수를 초기화하지 않고 사용하여 예기치 않은 오류가 발생하는 보안약점'},
 {'item_number': 43,
  'identifier': 'KISA-COD-05',
  'category': '코드오류',
  'name': '신뢰할 수 없는 데이터의 역직렬화',
  'description': '악의적인 코드가 삽입·수정된 직렬화 데이터를 적절한 검증 없이 역직렬화하여 발생하는 보안약점'},
 {'item_number': 44,
  'identifier': 'KISA-ENC-01',
  'category': '캡슐화',
  'name': '잘못된 세션에 의한 데이터 정보노출',
  'description': '잘못된 세션에 의해 인가되지 않은 사용자에게 중요정보가 노출 가능한 보안약점'},
 {'item_number': 45,
  'identifier': 'KISA-ENC-02',
  'category': '캡슐화',
  'name': '제거되지 않고 남은 디버그 코드',
  'description': '디버깅을 위한 코드를 제거하지 않아 인가되지 않은 사용자에게 중요정보가 노출 가능한 보안약점'},
 {'item_number': 46,
  'identifier': 'KISA-ENC-03',
  'category': '캡슐화',
  'name': 'Public 메서드로부터 반환된 Private 배열',
  'description': 'Public 메서드에서 Private 배열을 반환하여 배열의 주소 값이 외부에 노출되고 배열 값을 외부에서 수정 가능한 보안약점'},
 {'item_number': 47,
  'identifier': 'KISA-ENC-04',
  'category': '캡슐화',
  'name': 'Private 배열에 Public 데이터 할당',
  'description': 'Public 데이터 또는 메서드 인자가 Private 배열에 저장되어 해당 배열을 외부에서 접근하여 수정 가능한 보안약점'},
 {'item_number': 48,
  'identifier': 'KISA-API-01',
  'category': 'API 오용',
  'name': 'DNS lookup에 의존한 보안결정',
  'description': 'DNS lookup으로 보안결정을 수행할 때 악의적으로 변조된 DNS 정보로 예기치 않은 보안위협에 노출되는 보안약점'},
 {'item_number': 49,
  'identifier': 'KISA-API-02',
  'category': 'API 오용',
  'name': '취약한 API 사용',
  'description': '취약한 함수를 사용해서 예기치 않은 보안위협에 노출되는 보안약점'}]
